name: flutter_firebase_kit
description: Boilerplate stuff for creating flutter + firebase apps
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  google_sign_in: ^5.0.1
  firebase_core: ^1.0.3
  firebase_auth: ^3.3.5
  firebase_storage: ^10.2.5
  cloud_firestore: ^3.1.6
  provider: ^6.0.2
  uuid: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Heebo
      fonts:
        - asset: assets/fonts/heebo/Heebo-Thin.ttf
          weight: 100
        - asset: assets/fonts/heebo/Heebo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/heebo/Heebo-Light.ttf
          weight: 300
        - asset: assets/fonts/heebo/Heebo-Regular.ttf
          weight: 400
        - asset: assets/fonts/heebo/Heebo-Medium.ttf
          weight: 500
        - asset: assets/fonts/heebo/Heebo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/heebo/Heebo-Bold.ttf
          weight: 700
        - asset: assets/fonts/heebo/Heebo-ExtraBold.ttf
          weight: 800
    - family: Karla
      fonts:
        - asset: assets/fonts/karla/Karla-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/karla/Karla-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/karla/Karla-Light.ttf
          weight: 300
        - asset: assets/fonts/karla/Karla-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/karla/Karla-Regular.ttf
          weight: 400
        - asset: assets/fonts/karla/Karla-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/karla/Karla-Medium.ttf
          weight: 500
        - asset: assets/fonts/karla/Karla-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/karla/Karla-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/karla/Karla-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/karla/Karla-Bold.ttf
          weight: 700
        - asset: assets/fonts/karla/Karla-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/karla/Karla-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/karla/Karla-ExtraBoldItalic.ttf
          weight: 800
          style: italic
